appVersion : apps/1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-application
spec:
  selector:
    matchLabels:
      project: kgb
  template:
    matadata:
      labels:
        project: kgb
    spec:
      containers:
        - name: kgb-web
          image: garymorozov/k8sphp:version1
          ports:
            - containerPort: 80
              
